# Enhanced 5G Traffic Statistics Generator Configuration
# Demonstrates all advanced features: traffic mix, time-of-day, impairments

# Basic simulation parameters
duration_sec: 300  # 5 minutes for demonstration
interval_ms: 1000  # 1 second intervals
num_users: 10000   # Large scale simulation
bandwidth_per_user_mbps: 3.0
random_seed: 42

# Performance settings
use_high_performance: true
use_vectorized: true
max_cores: 8

# Output configuration
output_file: "output/enhanced_5g_simulation.csv"
output_format: "csv"
generate_report: true

# Enhanced traffic profiles with mix reflections
profiles:
  - name: "eMBB"
    traffic_share: 0.70
    packet_size_bytes: [1400, 800, 200]
    packet_size_pct: [75, 15, 10]
    ul_dl_ratio: 0.12
    flows_per_user: 3
    qos_5qi: 9
    protocol: "TCP"
    priority: 2
    burstiness_factor: 1.3
    session_duration_sec: 30.0
    inter_arrival_pattern: "poisson"
    
  - name: "URLLC"
    traffic_share: 0.15
    packet_size_bytes: [88, 120]
    packet_size_pct: [80, 20]
    ul_dl_ratio: 1.0
    flows_per_user: 1
    qos_5qi: 1
    protocol: "UDP"
    priority: 1
    burstiness_factor: 1.1
    session_duration_sec: 2.0
    inter_arrival_pattern: "deterministic"
    
  - name: "mMTC"
    traffic_share: 0.10
    packet_size_bytes: [60, 40]
    packet_size_pct: [70, 30]
    ul_dl_ratio: 4.0
    flows_per_user: 1
    qos_5qi: 7
    protocol: "UDP"
    priority: 3
    burstiness_factor: 2.0
    session_duration_sec: 0.5
    inter_arrival_pattern: "burst"
    
  - name: "VoNR"
    traffic_share: 0.05
    packet_size_bytes: [60]
    packet_size_pct: [100]
    ul_dl_ratio: 1.0
    flows_per_user: 1
    qos_5qi: 2
    protocol: "RTP"
    priority: 1
    burstiness_factor: 1.0
    session_duration_sec: 120.0
    inter_arrival_pattern: "periodic"

# Time-of-day variation patterns (24-hour normalized multipliers)
time_of_day:
  eMBB: [0.2, 0.2, 0.1, 0.1, 0.2, 0.4, 0.7, 0.9, 1.0, 1.1, 1.0, 1.0, 1.1, 1.0, 0.9, 0.9, 1.0, 1.2, 1.4, 1.3, 1.0, 0.8, 0.5, 0.3]
  URLLC: [0.8, 0.7, 0.6, 0.6, 0.7, 0.9, 1.1, 1.2, 1.3, 1.3, 1.2, 1.1, 1.2, 1.3, 1.2, 1.1, 1.2, 1.3, 1.2, 1.1, 1.0, 0.9, 0.9, 0.8]
  mMTC: [1.2, 1.1, 1.0, 1.0, 1.1, 1.0, 0.9, 0.8, 0.7, 0.8, 0.9, 1.0, 1.0, 1.0, 1.1, 1.2, 1.3, 1.2, 1.1, 1.2, 1.3, 1.3, 1.3, 1.2]
  VoNR: [0.3, 0.2, 0.2, 0.2, 0.3, 0.5, 0.8, 1.0, 1.2, 1.1, 1.0, 1.0, 1.1, 1.0, 0.9, 1.0, 1.1, 1.3, 1.2, 1.0, 0.8, 0.6, 0.4, 0.3]

# Event-driven traffic spikes
events:
  eMBB:
    - start_interval: 60   # 1 minute in
      end_interval: 120    # 2 minutes duration
      multiplier: 2.0      # Double the traffic
  URLLC:
    - start_interval: 180  # 3 minutes in
      end_interval: 210    # 30 seconds duration
      multiplier: 1.5      # 50% increase

# Network impairments (loss, latency, jitter)
impairments:
  eMBB:
    loss_rate: 0.001        # 0.1% packet loss
    latency_ms:
      mean: 15
      std: 2.0
    jitter_ms:
      std: 1.5
      
  URLLC:
    loss_rate: 0.0001       # 0.01% packet loss (very low)
    latency_ms:
      mean: 1
      std: 0.2
    jitter_ms:
      std: 0.1
      
  mMTC:
    loss_rate: 0.01         # 1% packet loss (higher tolerance)
    latency_ms:
      mean: 50
      std: 10.0
    jitter_ms:
      std: 5.0
      
  VoNR:
    loss_rate: 0.0005       # 0.05% packet loss
    latency_ms:
      mean: 20
      std: 3.0
    jitter_ms:
      std: 2.0