duration_sec: 120
interval_ms: 1000
num_users: 5000
bandwidth_per_user_mbps: 2.5
random_seed: 42
output_file: "output/5g_traffic_stats.csv"
output_format: "csv"
use_vectorized: true
generate_report: true

profiles:
  - name: "eMBB"
    traffic_share: 0.80
    packet_size_bytes: [1400, 200]
    packet_size_pct: [85, 15]
    ul_dl_ratio: 0.15
    flows_per_user: 3
    qos_5qi: 9
    
  - name: "URLLC"
    traffic_share: 0.15
    packet_size_bytes: [88]
    packet_size_pct: [100]
    ul_dl_ratio: 1.0
    flows_per_user: 1
    qos_5qi: 3
    
  - name: "mMTC"
    traffic_share: 0.05
    packet_size_bytes: [60]
    packet_size_pct: [100]
    ul_dl_ratio: 4.0
    flows_per_user: 1
    qos_5qi: 7