# Monthly 5G Traffic Statistics Configuration
# 30 days of realistic traffic data with 1-minute intervals

# Simulation parameters for 1 month
duration_sec: 2592000  # 30 days = 30 * 24 * 60 * 60 seconds
interval_ms: 60000     # 1 minute intervals
num_users: 1000        # 1,000 users for 10 Gbps target
bandwidth_per_user_mbps: 10.0  # 10 Mbps per user = 10 Gbps total
random_seed: 42

# High-performance settings
use_high_performance: true
use_vectorized: true
max_cores: 8

# Output configuration
output_file: "output/monthly_5g_traffic.csv"
output_format: "csv"
generate_report: true

# Realistic 5G traffic profiles with proper distribution
profiles:
  - name: "eMBB"
    traffic_share: 0.75        # 75% of traffic (video, web, apps)
    packet_size_bytes: [1400, 800, 200]
    packet_size_pct: [70, 20, 10]
    ul_dl_ratio: 0.15          # 15% uplink, 85% downlink
    flows_per_user: 3
    qos_5qi: 9
    protocol: "TCP"
    priority: 2
    burstiness_factor: 1.4     # Moderate burstiness for video/web
    session_duration_sec: 45.0
    inter_arrival_pattern: "poisson"
    
  - name: "URLLC"
    traffic_share: 0.10        # 10% critical applications
    packet_size_bytes: [88, 120, 64]
    packet_size_pct: [60, 30, 10]
    ul_dl_ratio: 1.0           # Equal UL/DL for control traffic
    flows_per_user: 1
    qos_5qi: 1
    protocol: "UDP"
    priority: 1
    burstiness_factor: 1.1     # Low burstiness for reliability
    session_duration_sec: 5.0
    inter_arrival_pattern: "deterministic"
    
  - name: "mMTC"
    traffic_share: 0.10        # 10% IoT/sensor traffic
    packet_size_bytes: [60, 40, 80]
    packet_size_pct: [60, 30, 10]
    ul_dl_ratio: 3.0           # Heavy uplink for sensor data
    flows_per_user: 1
    qos_5qi: 7
    protocol: "UDP"
    priority: 3
    burstiness_factor: 2.5     # High burstiness for IoT
    session_duration_sec: 1.0
    inter_arrival_pattern: "burst"
    
  - name: "VoNR"
    traffic_share: 0.05        # 5% voice traffic
    packet_size_bytes: [60]
    packet_size_pct: [100]
    ul_dl_ratio: 1.0           # Equal UL/DL for voice
    flows_per_user: 1
    qos_5qi: 2
    protocol: "RTP"
    priority: 1
    burstiness_factor: 1.0     # Steady voice traffic
    session_duration_sec: 180.0
    inter_arrival_pattern: "periodic"

# Time-of-day variation patterns (24-hour cycles)
# Values represent traffic multipliers for each hour
time_of_day:
  # eMBB: Heavy usage during business hours and evening entertainment
  eMBB: [0.15, 0.12, 0.10, 0.10, 0.15, 0.35, 0.65, 0.85, 1.0, 1.1, 1.05, 1.0, 
         1.15, 1.05, 0.95, 0.90, 1.0, 1.25, 1.45, 1.35, 1.1, 0.85, 0.55, 0.25]
  
  # URLLC: More consistent, slight increase during business hours
  URLLC: [0.75, 0.70, 0.65, 0.65, 0.70, 0.85, 1.05, 1.15, 1.25, 1.30, 1.20, 1.10,
          1.20, 1.25, 1.15, 1.10, 1.15, 1.25, 1.20, 1.10, 1.0, 0.90, 0.85, 0.80]
  
  # mMTC: IoT traffic peaks at night (automated processes) and during business
  mMTC: [1.15, 1.10, 1.05, 1.0, 1.05, 1.0, 0.85, 0.75, 0.70, 0.75, 0.85, 0.95,
         0.95, 0.90, 1.0, 1.10, 1.20, 1.15, 1.05, 1.10, 1.20, 1.25, 1.20, 1.15]
  
  # VoNR: Voice peaks during business hours and evening
  VoNR: [0.25, 0.20, 0.15, 0.15, 0.25, 0.45, 0.75, 0.95, 1.15, 1.10, 1.05, 1.0,
         1.10, 1.05, 0.95, 0.90, 1.05, 1.25, 1.20, 1.0, 0.80, 0.60, 0.40, 0.30]

# Weekly patterns could be added here for longer-term variations
# For now, we'll use the daily pattern repeated

# Network impairments - realistic values for each traffic class
impairments:
  eMBB:
    loss_rate: 0.002           # 0.2% packet loss (acceptable for video/web)
    latency_ms:
      mean: 18                 # 18ms average latency
      std: 3.0                 # 3ms standard deviation
    jitter_ms:
      std: 2.0                 # 2ms jitter standard deviation
      
  URLLC:
    loss_rate: 0.0001          # 0.01% packet loss (very low for critical apps)
    latency_ms:
      mean: 2                  # 2ms average latency (ultra-low)
      std: 0.3                 # 0.3ms standard deviation
    jitter_ms:
      std: 0.15                # 0.15ms jitter (very low)
      
  mMTC:
    loss_rate: 0.005           # 0.5% packet loss (higher tolerance for IoT)
    latency_ms:
      mean: 100                # 100ms average latency (relaxed for IoT)
      std: 20.0                # 20ms standard deviation
    jitter_ms:
      std: 8.0                 # 8ms jitter standard deviation
      
  VoNR:
    loss_rate: 0.0008          # 0.08% packet loss (low for voice quality)
    latency_ms:
      mean: 25                 # 25ms average latency (acceptable for voice)
      std: 4.0                 # 4ms standard deviation
    jitter_ms:
      std: 3.0                 # 3ms jitter standard deviation

# Event-driven traffic spikes (simulating special events during the month)
events:
  eMBB:
    # Weekend evening spike (day 6-7, hours 19-22)
    - start_interval: 8700     # Day 6, hour 19 (6*24*60 + 19*60)
      end_interval: 8880       # 3 hours later
      multiplier: 2.2          # 120% increase for weekend entertainment
    
    # Another weekend spike (day 13-14)  
    - start_interval: 18900    # Day 13, hour 19
      end_interval: 19080      # 3 hours later
      multiplier: 2.0          # 100% increase
      
    # Month-end event (day 28, prime time)
    - start_interval: 40500    # Day 28, hour 20
      end_interval: 40620      # 2 hours later
      multiplier: 2.5          # 150% increase for special event

  URLLC:
    # Business day spike (day 15, business hours)
    - start_interval: 21600    # Day 15, hour 10
      end_interval: 21720      # 2 hours later  
      multiplier: 1.4          # 40% increase for critical operations