# Yearly 5G Traffic Statistics Configuration
# Full year (365 days) of realistic traffic data with optimized intervals

# Simulation parameters for 1 full year
duration_sec: 31536000   # 365 days = 365 * 24 * 60 * 60 seconds
interval_ms: 300000      # 5-minute intervals (optimized for file size vs. granularity)
num_users: 1000          # 1,000 users for 10+ Gbps target
bandwidth_per_user_mbps: 12.0  # 12 Mbps per user = 12 Gbps total (accounting for variations)
random_seed: 2024        # Year-specific seed for reproducibility

# High-performance settings - CRITICAL for yearly simulation
use_high_performance: true
use_vectorized: true
max_cores: 8

# Output configuration
output_file: "output/yearly_5g_traffic_2024.csv"
output_format: "csv"
generate_report: true

# Chart and analysis configuration
generate_charts: true
analyze_patterns: true
charts:
  formats: ["png", "html", "svg"]
  dpi: 300
  figsize: [16, 12]
  # Performance optimization settings for large yearly dataset
  max_points: 8000              # Downsample to 8k points for yearly charts
  sampling_strategy: "time_based" # Use time-based aggregation for year-long data
  preserve_peaks: true          # Keep important peaks/valleys
  time_aggregation: "auto"      # Auto-determine hourly/daily aggregation
analysis:
  peak_threshold: 1.8
  pattern_sensitivity: 0.15
  anomaly_threshold: 2.5

# Optimized 5G traffic profiles for yearly simulation
profiles:
  - name: "eMBB"
    traffic_share: 0.78        # 78% of traffic (dominant for consumer use)
    packet_size_bytes: [1400, 800, 400, 200]
    packet_size_pct: [65, 20, 10, 5]
    ul_dl_ratio: 0.14          # 14% uplink, 86% downlink
    flows_per_user: 3
    qos_5qi: 9
    protocol: "TCP"
    priority: 2
    burstiness_factor: 1.5     # Higher burstiness for video streaming variations
    session_duration_sec: 60.0
    inter_arrival_pattern: "poisson"
    
  - name: "URLLC"
    traffic_share: 0.08        # 8% critical applications (industrial, automotive)
    packet_size_bytes: [88, 120, 64, 100]
    packet_size_pct: [50, 25, 15, 10]
    ul_dl_ratio: 1.2           # Slightly UL-heavy for control feedback
    flows_per_user: 1
    qos_5qi: 1
    protocol: "UDP"
    priority: 1
    burstiness_factor: 1.05    # Very low burstiness for reliability
    session_duration_sec: 8.0
    inter_arrival_pattern: "deterministic"
    
  - name: "mMTC"
    traffic_share: 0.10        # 10% IoT/sensor traffic (growing segment)
    packet_size_bytes: [60, 40, 80, 32]
    packet_size_pct: [55, 25, 15, 5]
    ul_dl_ratio: 4.0           # Heavy uplink for sensor data
    flows_per_user: 1
    qos_5qi: 7
    protocol: "UDP"
    priority: 3
    burstiness_factor: 3.0     # High burstiness for IoT batch transmissions
    session_duration_sec: 2.0
    inter_arrival_pattern: "burst"
    
  - name: "VoNR"
    traffic_share: 0.04        # 4% voice traffic (declining with messaging apps)
    packet_size_bytes: [60, 80]
    packet_size_pct: [85, 15]
    ul_dl_ratio: 1.0           # Equal UL/DL for voice
    flows_per_user: 1
    qos_5qi: 2
    protocol: "RTP"
    priority: 1
    burstiness_factor: 1.0     # Steady voice traffic
    session_duration_sec: 240.0
    inter_arrival_pattern: "periodic"

# Comprehensive time-of-day variation patterns
# 24-hour cycles with realistic business/residential patterns
time_of_day:
  # eMBB: Consumer-driven with entertainment peaks
  eMBB: [0.12, 0.10, 0.08, 0.08, 0.12, 0.30, 0.55, 0.75, 0.90, 1.00, 0.95, 0.90,
         1.05, 0.95, 0.85, 0.80, 0.90, 1.15, 1.35, 1.25, 1.05, 0.80, 0.50, 0.20]
  
  # URLLC: Business-hours focused with industrial operations
  URLLC: [0.70, 0.65, 0.60, 0.60, 0.65, 0.80, 1.00, 1.10, 1.20, 1.25, 1.15, 1.05,
          1.15, 1.20, 1.10, 1.05, 1.10, 1.20, 1.15, 1.05, 0.95, 0.85, 0.80, 0.75]
  
  # mMTC: IoT patterns with automated processes during off-peak
  mMTC: [1.10, 1.05, 1.00, 0.95, 1.00, 0.95, 0.80, 0.70, 0.65, 0.70, 0.80, 0.90,
         0.90, 0.85, 0.95, 1.05, 1.15, 1.10, 1.00, 1.05, 1.15, 1.20, 1.15, 1.10]
  
  # VoNR: Voice peaks during business and evening social hours
  VoNR: [0.20, 0.15, 0.12, 0.12, 0.20, 0.40, 0.70, 0.90, 1.10, 1.05, 1.00, 0.95,
         1.05, 1.00, 0.90, 0.85, 1.00, 1.20, 1.15, 0.95, 0.75, 0.55, 0.35, 0.25]

# Weekly patterns (7-day cycles) - multipliers for each day of week
weekly_patterns:
  # Monday=1, Sunday=7
  eMBB: [1.0, 1.05, 1.10, 1.15, 1.20, 1.35, 1.25]    # Peak on weekends
  URLLC: [1.15, 1.20, 1.25, 1.20, 1.15, 0.80, 0.70]  # Business weekdays
  mMTC: [1.05, 1.05, 1.10, 1.10, 1.05, 1.15, 1.20]   # Steady with weekend batch jobs
  VoNR: [1.10, 1.15, 1.20, 1.15, 1.25, 1.30, 1.20]   # Social patterns

# Seasonal patterns (12-month cycles) - account for yearly variations
seasonal_patterns:
  # Jan=1, Dec=12 - normalized multipliers
  eMBB: [0.85, 0.88, 0.95, 1.00, 1.05, 1.10, 1.15, 1.12, 1.08, 1.02, 0.95, 0.90]
  URLLC: [0.95, 0.98, 1.05, 1.10, 1.15, 1.12, 1.08, 1.05, 1.10, 1.08, 1.00, 0.92]
  mMTC: [1.05, 1.08, 1.10, 1.12, 1.15, 1.10, 1.05, 1.08, 1.12, 1.15, 1.10, 1.05]
  VoNR: [0.90, 0.95, 1.00, 1.05, 1.10, 1.05, 1.00, 0.98, 1.02, 1.08, 1.05, 1.15]

# Major events throughout the year (interval-based for 5-minute intervals)
# Total intervals per year: 31536000 / 300 = 105,120 intervals
events:
  eMBB:
    # New Year's Eve (Dec 31, 9 PM - Jan 1, 2 AM)
    - start_interval: 104640    # Dec 31, 9 PM
      end_interval: 104700      # 5 hours later
      multiplier: 2.8           # 180% increase
    
    # Valentine's Day evening (Feb 14, 6-11 PM)  
    - start_interval: 13392     # Approx Feb 14, 6 PM
      end_interval: 13452       # 5 hours later
      multiplier: 1.8           # 80% increase
    
    # Summer holidays (July 4th weekend)
    - start_interval: 52800     # July 4 area
      end_interval: 53280       # Extended weekend
      multiplier: 2.2           # 120% increase
    
    # Black Friday shopping (Nov 29, all day surge)
    - start_interval: 89280     # Nov 29 area
      end_interval: 89568       # 24 hours
      multiplier: 2.5           # 150% increase
    
    # Christmas/New Year season (Dec 20-31)
    - start_interval: 103680    # Dec 20
      end_interval: 104640      # Dec 31
      multiplier: 1.6           # 60% sustained increase

  URLLC:
    # Business quarters end (Mar 31, Jun 30, Sep 30, Dec 31)
    - start_interval: 21600     # Q1 end
      end_interval: 21888
      multiplier: 1.4
    - start_interval: 43200     # Q2 end  
      end_interval: 43488
      multiplier: 1.4
    - start_interval: 65280     # Q3 end
      end_interval: 65568
      multiplier: 1.4
    - start_interval: 104640    # Q4 end
      end_interval: 104928
      multiplier: 1.5

  mMTC:
    # Spring IoT deployment surge (March-April)
    - start_interval: 17280     # March
      end_interval: 25920       # April
      multiplier: 1.3
    
    # Fall harvest/monitoring season (September-October)
    - start_interval: 64800     # September  
      end_interval: 73440       # October
      multiplier: 1.4

# Realistic network impairments for yearly simulation
impairments:
  eMBB:
    loss_rate: 0.0025          # 0.25% average packet loss
    latency_ms:
      mean: 20                 # 20ms average latency
      std: 4.0                 # 4ms standard deviation
    jitter_ms:
      std: 2.5                 # 2.5ms jitter standard deviation
      
  URLLC:
    loss_rate: 0.0001          # 0.01% packet loss (ultra-reliable)
    latency_ms:
      mean: 1.5                # 1.5ms average latency (ultra-low)
      std: 0.25                # 0.25ms standard deviation
    jitter_ms:
      std: 0.12                # 0.12ms jitter (minimal)
      
  mMTC:
    loss_rate: 0.008           # 0.8% packet loss (higher tolerance)
    latency_ms:
      mean: 120                # 120ms average latency (relaxed)
      std: 25.0                # 25ms standard deviation
    jitter_ms:
      std: 10.0                # 10ms jitter standard deviation
      
  VoNR:
    loss_rate: 0.001           # 0.1% packet loss (voice quality)
    latency_ms:
      mean: 30                 # 30ms average latency (acceptable for voice)
      std: 5.0                 # 5ms standard deviation
    jitter_ms:
      std: 4.0                 # 4ms jitter standard deviation

# Performance optimization notes:
# - 5-minute intervals reduce data points from 31.5M to 105K (manageable)
# - Expected file size: ~50-70 MB CSV
# - Expected execution time: <0.1 seconds
# - Memory usage: <2 GB RAM
# - Realistic for single-machine processing